config/routes.rb
Rails.application.routes.draw do
  root 'listings#index'
  resources :listings
  get 'search', to: 'search#search'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/listing.rb
class Listing
  include Elasticsearch::Model 
  include Elasticsearch::Model::Callbacks
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :beds, type: Integer
  field :baths, type: Integer

  settings do
    mappings dynamic: false do
      indexes :beds, type: :integer
      indexes :baths, type: :integer
    end
  end

  validates_presence_of :beds, on: :create,  message: 'beds must be present'
  validates_presence_of :baths, on: :create,  message: 'baths must be present'
  validates_numericality_of :beds, greater_than: 0, message: 'Beds must be greater than Zero'
  validates_numericality_of :baths, greater_than: 0, message: 'Baths must be greater than Zero'

  # def self.search(search_params)
  #   Listing.search(
  #     index: "beds",
  #       body: {
  #         query: {
  #           range: {
  #               beds: {
  #                   gte: search_params[:min_beds],
  #                   lte: search_params[:max_beds]
  #               },
  #               baths: {
  #                   gte: search_params[:min_baths],
  #                     lte: search_params[:max_baths]
  #               }
  #           }
  #         }
  #       }
  #     )
  #   # Listing.where(:beds.gte => search_params[:min_beds]).and(:beds.lte => search_params[:max_beds]).and(:baths.gte => search_params[:min_baths]).and(:baths.lte => search_params[:max_baths])
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:beds, :baths)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:min_beds].nil? && params[:min_baths].nil?
      @listings = []
    else
      @listings = Listing.search(
      index: "beds",
        body: {
          query: {
            range: {
                beds: {
                    gte: search_params[:min_beds],
                    lte: search_params[:max_beds]
                },
                baths: {
                    gte: search_params[:min_baths],
                      lte: search_params[:max_baths]
                }
            }
          }
        }
      )
    end
  end

  private

  def search_params
    params.permit(:min_beds, :max_beds, :min_baths, :max_baths)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElasticSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing) do |form| %>
  <% if listing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :beds, style: "display: block" %>
    <%= form.number_field :beds %>
  </div>

  <div>
    <%= form.label :baths, style: "display: block" %>
    <%= form.number_field :baths %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/_listing.html.erb
<div id="<%= dom_id listing %>">
  <p>
    <strong>Beds:</strong>
    <%= listing.beds %>
  </p>

  <p>
    <strong>Baths:</strong>
    <%= listing.baths %>
  </p>

</div>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render "form", listing: @listing %>

<br>

<div>
  <%= link_to "Show this listing", @listing %> |
  <%= link_to "Back to listings", listings_path %>
</div>

app/views/listings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Listings</h1>

<div id="listings">
  <% @listings.each do |listing| %>
    <%= render listing %>
    <p>
      <%= link_to "Show this listing", listing %>
    </p>
  <% end %>
</div>

<%= link_to "New listing", new_listing_path %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render "form", listing: @listing %>

<br>

<div>
  <%= link_to "Back to listings", listings_path %>
</div>

app/views/listings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @listing %>

<div>
  <%= link_to "Edit this listing", edit_listing_path(@listing) %> |
  <%= link_to "Back to listings", listings_path %>

  <%= button_to "Destroy this listing", @listing, method: :delete %>
</div>

app/views/search/_listing.html.erb
<div id="<%= dom_id listing %>">
  <p>
    <strong>Beds:</strong>
    <%= listing.beds %>
  </p>

  <p>
    <strong>Baths:</strong>
    <%= listing.baths %>
  </p>

</div>

app/views/search/search.html.erb
<%= form_with url: search_url, method: :get do |form| %>

  <div>
    <%= form.label 'Minimun beds', style: "display: block" %>
    <%= form.number_field :min_beds %>
  </div>

  <div>
    <%= form.label 'Maximum beds', style: "display: block" %>
    <%= form.number_field :max_beds %>
  </div>

  <div>
    <%= form.label 'Minimum baths', style: "display: block" %>
    <%= form.number_field :min_baths %>
  </div>

  <div>
    <%= form.label 'Maximum baths', style: "display: block" %>
    <%= form.number_field :max_baths %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<ul>
  <% @listings.each do |listing| %>
    <%= render listing %>
    <p>
      <%= link_to "Show this listing", listing %>
    </p>
  <% end %>
</ul>